config/routes.rb
Rails.application.routes.draw do

  resources :subjects, only: [:new, :create, :index, :show]
  resources :locations
  resources :profiles
  resource :session, only: [:new, :create, :destroy]
  resources :chats, only: [:index, :show] do
    resources :comments
  end
  resources :comments, only: [:create, :edit, :update, :destroy]
  resources :users do
    resources :chats
      post 'follow', to: 'following_relationships#create'
    delete 'follow', to: 'following_relationships#destroy'
  end
  get 'home/index', to: 'home#index', as: '/home'

  root 'landing#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :chat
  belongs_to :user
end

app/models/following_relationship.rb
class FollowingRelationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed_user, class_name: 'User'
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :locationable, polymorphic: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one :location, as: :locationable, dependent: :destroy
  has_many :subjects
  # has_many :subjects, as: :subjectable, dependent: :destroy
  accepts_nested_attributes_for :location
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :profile, dependent: :destroy
  has_many :locations, as: :locationable, dependent: :destroy
  has_many :chats
  has_many :comments
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true

  has_many :followed_user_relationships,
    foreign_key: :follower_id,
    class_name: 'FollowingRelationship'
  has_many :followed_users, through: :followed_user_relationships


  has_many :follower_relationships,
    foreign_key: :followed_user_id,
    class_name: 'FollowingRelationship'
  has_many :followers, through: :follower_relationships

  def following?(user)
    followed_user_ids.include?(user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  def index
    @chats = Chat.all.order(created_at: :desc)
  end

  def show
    @chat = Chat.find(params[:id])
  end

  def create
    user = current_user
    @chat = user.chats.build chat_params
    if @chat.save
      redirect_to profile_path user, notice: "Chat created"
    end
  end

  private
  def chat_params
    params.require(:chat).permit(:title, :description)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.all
  end

  def create
    chat = Chat.find(params[:chat_id])
    @comment = chat.comments.build comment_params
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to :back, notice: "Message posted"
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to chat_path(@comment.chat), notice: "Post Edited"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.delete
    redirect_to chat_path(@comment.chat)
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/following_relationships_controller.rb
class FollowingRelationshipsController < ApplicationController

  def create
    user = User.find(params[:user_id])
    current_user.followed_users << user
    redirect_to profile_path(user)
  end

  def destroy
    user = User.find(params[:user_id])
    current_user.followed_users.delete(user)
    redirect_to profile_path(user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include HomeHelper

  def index
    @users = User.all.order(created_at: :desc)
    @user = current_user
    @daily_quote = INSPIRATION.sample
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController



  def new
    # @profile = current_user.profile
    @location = Location.new
  end

  def create
    @user = current_user
    @profile = current_user.profile
    # binding.pry
    if params[:profile]
      @profile.build_location(location_params).save
      flash[:notice] = "Success"
      redirect_to profile_path(@user)
    # elsif params[:teacher]
    #   redirect_to root_path
    else
      redirect_to home_path
    end
  end

  private
  def location_params
    params.require(:location).permit(:address)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
    @profile = @user.profile
    @location = @profile.location
  end

  def new
    @user = current_user
    @profile = @user.profile
  end

  def create
  end

  def edit
    @user = current_user
    @profile = @user.profile
  end

  def update
    @user = current_user
    if @profile = current_user.profile
      @profile.update(profile_params)
      flash[:notice] = "Success!!"
      redirect_to profile_path(@user)
    else
      flash.now[:notice] = "Something went wrong :("
      render :edit
    end
  end

  private
  def profile_params
    params.require(:profile).permit(:bio, :image, :user_id, location_attriubtes: [:address, :suburb, :state, :country, :postcode])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create], raise: false

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to home_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:username, :email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create], raise: false

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @profile = @user.profile
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      @profile = Profile.new
      @profile.user_id = @user.id
      @profile.save
      redirect_to home_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  INSPIRATION = ["You can't have everything. Where would you put it?","The trouble with being punctual is that nobody's there to appreciate it.","If you are afraid of being lonely, don't try to be right.", "When you battle with your conscience and lose, you win.", "Human salvation lies in the hands of the creatively maladjusted.", "Hating people is like burning down your own home to get rid of a rat."]
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def follow_button(user)
    if current_user.following?(user)
      button_to 'Unfollow', user_follow_path(user), method: :delete
    else
      button_to 'Follow', user_follow_path(user)
    end
  end
end

app/views/chats/_chat.html.erb
<h4><%= link_to chat.title, chat_path(chat) %></h4>
<p><%= chat.description %></p>

app/views/chats/_form.html.erb
<%= form_for [user, Chat.new] do |f| %>
  <p><%= f.text_field :title, placeholder: "Enter chat name.." %></p>
  <p><%= f.text_area :description, placeholder: "Enter Chat description.." %></p>
  <%= f.submit %>
<% end %>

app/views/chats/index.html.erb
<% @chats.each do |chat| %>
  <h4><%= link_to chat.title, chat_path(chat) %></h4>
  <p><%= chat.description %></p>
<% end %>

app/views/chats/show.html.erb
<h3>A <%= @chat.title %> Chat</h3>
<p>Created by <%= link_to @chat.user.username, profile_path(@chat.user.profile) %>, <%= time_ago_in_words(@chat.created_at) + ' ago' %></p>
<hr>
<%= link_to "Back", chats_path %>
</br>
<%= render partial: 'comments/form' %>

<hr>
<%= render @chat.comments %>

app/views/comments/_comment.html.erb
<p></p>
<%= comment.body %>
<p> Posted by <%= link_to comment.user.username, profile_path(comment.user) %>, <%= time_ago_in_words(comment.created_at) + ' ago' %></p>

<% if comment.user == current_user %>
  <%= link_to "Edit", edit_comment_path(comment) %>
  <%= link_to "Delete", comment_path(comment), method: :delete %>
  <p>--------------</p>
<% else %>
  <p>--------------</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [@chat, Comment.new] do |f| %>
  <p><%= f.text_area :body, placeholder: "Chat away.." %></p>
  <%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<%= form_for @comment do |f| %>
  <p><%= f.text_area :body, placeholder: "Edit your post" %></p>
  <%= f.submit %>
<% end %>

app/views/home/index.html.erb
<h1>Dashboard</h1>
<p>See what's happening in your network</p>

<hr>
<% if signed_in? && @user.profile.bio %>
  <h3>Hey there <%= @user.username %>!</h3>
  <p><%= @daily_quote %></p>
<% elsif signed_in? && @user.profile.bio == nil %>
  <h3>Hey there <%= @user.username %>!</h3>
  <p>Don't forget to fill out your profile!</p>
  <%= link_to "Setup Profile!", new_profile_path %>
<% else %>
  <h3>Hey there!!</h3>
  <p>Sign up and get help today!!</p>
  <%= link_to "Sign Up", new_user_path %>
<% end %>
<hr>

<%= render @users %>

app/views/landing/index.html.erb
<h1>Student Chat</h1>
<p>Student to Student Portal</p>

<%= link_to "Enter Site", home_path %>

app/views/locations/_location.html.erb
<p><%= location.address %></p>

app/views/locations/new.html.erb
<%= form_for @location do |f| %>
  <%= f.text_field :address, placeholder: "Address..." %>
  <%= f.text_field :suburb, placeholder: "Suburb..." %>
  <%= f.text_field :state, placeholder: "State..." %>
  <%= f.text_field :country, placeholder: "Country..." %>
  <%= f.text_field :postcode, placeholder: "Postcode..." %>
  <%= submit_tag "Submit", name: params[:name] %>
<% end %>

app/views/profiles/create.html.erb
<h1>Profiles#create</h1>
<p>Find me in app/views/profiles/create.html.erb</p>

app/views/profiles/index.html.erb
<h1>Profiles#index</h1>
<p>Find me in app/views/profiles/index.html.erb</p>

app/views/profiles/new.html.erb
<h1>Hey <%= @user.username %>!!</h1>
<p>Fill out the rest of your profile!</p>

<%= form_for @user.profile do |f| %>
  <p><%= f.file_field :image %></p>
  <p><%= f.text_area :bio, placeholder: "Enter your bio..." %></p>
  <%= f.submit "Save!" %>
<% end %>

app/views/profiles/show.html.erb
<h1><%= @user.username %>s' profile page!</h1>

<% unless @user == current_user %>
  <%= follow_button(@user) %>
<% end %>
<hr>
<p><%= image_tag @profile.image.medium.url %></p>
<p>Email: <%= @user.email %></p>
<p>About me: <%= @profile.bio %></p>

<% if @user == current_user %>
  <hr>
  <h3>Start a chat?!</h3>
  <%= render partial: 'chats/form', locals: {user: @user} %>
<% end %>

<hr>

<% if @user == current_user %>
  <h3>My Chat's</h3>
<% else %>
  <h3><%= @user.username %>'s Chats</h3>
<% end %>
<%= render @user.chats %>


<% if @user == current_user %>
  <hr>
  <p>Add a location?</p>
  <p><%= link_to "Add Location", new_location_path(name: "profile") %></p>

  <% if @profile.location %>
    <p><%= render @profile.location %></p>
  <% end %>
<% else %>
  <% if @profile.location %>
    <h3><%= @user.username %>'s Locations</h3>
    <p><%= render @profile.location %></p>
  <% end %>
<% end %>



<%= link_to "Back", home_path %>

app/views/users/_user.html.erb
<% if user.profile.bio %>
  <div>
    <p><%= image_tag user.profile.image.thumb.url if user.profile.image %><%= link_to user.username, profile_path(user) %> joined <%= time_ago_in_words(user.created_at) + ' ago' %></p>
    <p><%= user.profile.bio if user.profile.bio%></p>
  </div>
  <hr>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |form| %>

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :username %>
    <%= form.text_field :username, require: true %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email, require: true %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password, require: true %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>